server:
   port: 9999
   tomcat: 
      max-threads: 128
      min-spare-threads: 64
    
spring:
   application:
      name: zuul-server

eureka:
   client:
      instance:
         leaseRenewalIntervalInSeconds: 10
         registryFetchIntervalSeconds: 5
      serviceUrl:
         defaultZone: http://navy:123456@127.0.0.1:6868/eureka

zuul:
   max:
      host:
         connections: 500
   host:
      maxTotalConnections: 200 # 最大连接数。默认值是200
      maxPerRouteConnections: 20 # 每个路由的最大连接数。默认20
   routes:
      # 标识你服务的名字，这里可以自己定义，一般方便和规范来讲还是跟自己服务的名字一样
      servic-rpc-a:
         # 服务映射的路径，通过这路径就可以从外部访问你的服务了，目的是为了不爆露你机器的IP，面向服务的路由了，给你选一个可用的出来，
         # 这里zuul是自动依赖hystrix，ribbon的，不是面向单机
         path: /user/**
         # 这里一定要是你Eureka注册中心的服务的名称，所以这里配置serviceId因为跟eureka结合了，如果单独使用zuul,那么就必须写自己机器的IP了，
         # 如url:http://localhost:8080/  这样的不好就是写死IP了，万一这IP挂了，这高可用性，服务注册那套东西就用不起来了
         serviceId: client-service
         # sensitive-headers:  #过滤掉客户端附带的headers相关属性。Zuul默认会过滤掉下面三个属性：Cookies、Set-Cookie、Authorization
    
   #servic-rpc-b:
      #  path: /service-rpc-b/**
      #  serviceId: hello-service
      ribbonIsolationStrategy: THREAD     
      threadPool:
         useSeparateThreadPools: true